name: build

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build_STM32F407IGHx:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: './librm'
          submodules: 'recursive'

      - name: Checkout empty project
        uses: actions/checkout@v4
        with:
          path: './stm32cube_template'
          submodules: 'recursive'
          repository: IRobot-EC-2024/stm32cube_template

      - name: Move source to template project
        run: mv librm stm32cube_template/stm32f407ighx

      - name: Add library target/link library
        run: |
          sed -i '42 a add_subdirectory(librm)' stm32cube_template/stm32f407ighx/CMakeLists.txt
          sed -i '66 a rm' stm32cube_template/stm32f407ighx/CMakeLists.txt

      - run: sudo apt install -y tree
      - run: tree ${{ github.workspace }}

      - name: Build
        run: |
          cmake stm32cube_template/stm32f407ighx -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Bstm32cube_template/stm32f407ighx/build -G "Unix Makefiles"
          cmake --build stm32cube_template/stm32f407ighx/build

  build_STM32H723VGTx:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc GNU Arm Embedded Toolchain
        uses: carlosperate/arm-none-eabi-gcc-action@v1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: './librm'
          submodules: 'recursive'

      - name: Checkout empty project
        uses: actions/checkout@v4
        with:
          path: './stm32cube_template'
          submodules: 'recursive'
          repository: IRobot-EC-2024/stm32cube_template

      - name: Move source to template project
        run: mv librm stm32cube_template/stm32h723vgtx

      - name: Add library target/link library
        run: |
          sed -i '42 a add_subdirectory(librm)' stm32cube_template/stm32h723vgtx/CMakeLists.txt
          sed -i '66 a rm' stm32cube_template/stm32h723vgtx/CMakeLists.txt

      - name: Build
        run: |
          cmake stm32cube_template/stm32h723vgtx -DCMAKE_BUILD_TYPE=$BUILD_TYPE -Bstm32cube_template/stm32h723vgtx/build -G "Unix Makefiles"
          cmake --build stm32cube_template/stm32h723vgtx/build

  build_general_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: '.'
          submodules: 'recursive'

      - name: Build
        run: cmake . -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE && cmake --build build -j
